language: node_js
node_js:
- 6
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
- npm install typings
- npm install protractor
- npm install http-server -g
- npm install
script:
- npm run tslint
- npm test
- npm run build:local
- http-server dist/ -p 3000 &
- npm run protractor