language: node_js
node_js:
- 6
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
- npm install typings
- npm install
script:
- npm run tslint
- npm test
- npm run build:local