sudo: required
language: node_js
node_js:
- 6
install:
- npm install typings
- npm install protractor
- npm install http-server -g
- npm install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script:
- npm run tslint
- npm test
- npm run build:local
- http-server dist/ -p 3000 &
- npm run protractor
cache:
  directories:
    - node_modules